#!/usr/bin/env ruby

# we change the working dir to project folder so that all files where bundler expects
Dir.chdir(File.dirname(__FILE__) + '/..') do
    require_relative '../app.rb'
    require_relative '../app/cli/setup.rb'
    FmCli::Cli.start(ARGV)
end

